### ISSUE TITLE
[Error/Bug] undefined method '>>'

### ISSUE THREAD

**Issue by lolgear** [mojombo/grit#185]
code:
def MainWork
    git_object = Grit::Repo.new('/absolute/path/to/directory/where/lay/git/repo')
    p git_object.commits # here error <-!!!
end

error:
`unpack_object_header_gently': undefined method`>>' for "x":String (NoMethodError)

**Comment by mraaroncruz** [comment]
I'm using https://github.com/pythonandchips/git-presenter and getting the same error with:
- `ruby 2.1.0`
- `ruby 2.0.0-p353`

but it works with `ruby 1.9.3-p448`

I am not invested in either project to look any further, but I hope this helps

I'm on OSX 10.9.1

``` bash
/Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:108:in `unpack_object_header_gently': undefined method `>>' for "x":String (NoMethodError)
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:56:in `get_raw_object'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/internal/loose.rb:32:in `[]'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:84:in `block in get_raw_object_by_sha1'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:83:in `each'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:83:in `get_raw_object_by_sha1'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:334:in `walk_log'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:287:in `log'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby/repository.rb:306:in `rev_list'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby.rb:70:in `block in rev_list'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby.rb:211:in `block in try_run'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby.rb:210:in `try_run'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/git-ruby.rb:70:in `rev_list'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/commit.rb:120:in `find_all'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/grit-2.5.0/lib/grit/repo.rb:381:in `commits'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_presenter-0.4.0/lib/git_presenter/controller.rb:48:in `create_slides'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_presenter-0.4.0/lib/git_presenter/controller.rb:9:in `initialise_presentation'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_presenter-0.4.0/lib/git_presenter.rb:18:in `execute'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_presenter-0.4.0/bin/git-presenter:8:in `<top (required)>'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/bin/git-presenter:23:in `load'
        from /Users/aaron/.rbenv/versions/2.0.0-p353/bin/git-presenter:23:in `<main>'
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See https://github.com/mojombo/grit/pull/183
